; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    bodmer/TFT_eSPI @ ^2.5.43
    https://github.com/DFRobot/DFRobotDFPlayerMini.git
build_flags =
  -D USER_SETUP_LOADED=1 ; Carrega o arquivo de configuração personalizado
  -D ILI9488_DRIVER=1 ; Define o driver do display
  -D TFT_BL=32            ; Pino do Backlight (opcional)
  -D TFT_MISO=19 ; Pino Master In Slave Out (MISO)
  -D TFT_MOSI=23 ; Pino Master Out Slave In (MOSI)
  -D TFT_SCLK=18 ; Pino Serial Clock (SCLK)
  -D TFT_CS=15 ; Pino Chip Select do display
  -D TFT_DC=2 ; Pino Data/Command
  -D TFT_RST=4 ; Pino Reset
  -D TOUCH_CS=21          ; Pino Chip Select do Touch
  -D SPI_FREQUENCY=27000000 ; Frequência segura para o ILI9488
  -D SPI_TOUCH_FREQUENCY=2500000 ; Frequência para o touch (pode ser menor que a do display)
  -D LOAD_GLCD=1  ; Carrega fontes básicas
  -D LOAD_FONT2=1
  -D LOAD_FONT4=1